### ISSUE TITLE
Cannot import via ES Module

### ISSUE THREAD

**Issue by Jack-Works** [vultix/ts-results#37]
node -v
v16.8.0

cat .\x.mjs
```js
import {Err} from 'ts-results'
```

node .\x.mjs
```
import {Err} from 'ts-results'
        ^^^
SyntaxError: Named export 'Err' not found. The requested module 'ts-results' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ts-results';
const {Err} = pkg;
```

**Comment by jstasiak** [comment]
Same here, Node.js 17.5.0, pure ESM package, `node --experimental-vm-modules` enabled and `ts-results` 3.3.0. I'd be happy to produce a patch for this but right now I have no idea how to make this package ESM-compatible while retaining CommonJS support.

**Comment by jstasiak** [comment]
Hey all, since I really needed this addressed quickly I published an ESM-only version of this package to NPM under the name of `ts-results-es`. This is the change that makes the package importable by ESM packages: https://github.com/lune-climate/ts-results-es/commit/0be48c527e86c6694c6c94576264134fcffb07de

I don't intend the package to be a long running fork of `ts-results` and I'm happy to drop it the moment `ts-results` works nicely with ESM.

**Comment by Jack-Works** [comment]
@jstasiak sorry but your version is still broken. change package.json is not enough, you need also to add all file extensions.

**Comment by jstasiak** [comment]
Hey @Jack-Works I forgot to mention, I'm running `node` with `--experimental-specifier-resolution=node` enabled.

You're right the extensions are needed in general, this is good enough for my use case right now.

**Comment by jstasiak** [comment]
@Jack-Works this should work without `--experimental-specifier-resolution=node` in both ESM and CJS modes: https://github.com/lune-climate/ts-results-es/pull/5

I pushed it to NPM as ts-results-es@3.3.1-alpha.1 and it'd be great if I got a confirmation it works for you. If it does I'll create a PR in this repository.

**Comment by jstasiak** [comment]
https://github.com/vultix/ts-results/pull/49 should resolve this

**Comment by jacoobes** [comment]
Any update on this?

**Comment by jstasiak** [comment]
For what it's worth you can use our ESM-compatible fork for the time being (https://www.npmjs.com/package/ts-results-es). I'd love the fork to become unnecessary though.

**Comment by jacoobes** [comment]
> For what it's worth you can use our ESM-compatible fork for the time being (https://www.npmjs.com/package/ts-results-es). I'd love the fork to become unnecessary though.

Oh, didn't see this. Much love, thank you so much! hoping this will be merged sooner or later
